[project]
name = "comfyui-promptlist"
description = "Custom node to manage prompts in YAML format."
<<<<<<< HEAD
version = "1.2.0"
=======
version = "1.1.2"
>>>>>>> aff35ca03de77cf5e7f6882b9993bd4c54ff2734
license = { file = "LICENSE.txt" }

[project.urls]
Repository = "https://github.com/NakamuraShippo/ComfyUI-PromptList"

[tool.comfy]
PublisherId = "nakamurashippo"
DisplayName = "ComfyUI-PromptList"
Icon = ""
